# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Madison Co Quick Lube
tagline:          '1601 Foxhaven Dr'
description:      'Superior sevice with a smile.'
url:              http://madisonquicklube.com

author:
  name:           'xtoddx'
  url:            https://twitter.com/xtoddx

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
